function(override_cache var val)
  if(DEFINED ${var})
    get_property(type CACHE ${var} PROPERTY TYPE)
    get_property(doc CACHE ${var} PROPERTY HELPSTRING)
    set(${var} ${val} CACHE ${type} "${doc}" FORCE)
  else()
    message(FATAL_ERROR "'${var}' is not defined")
  endif()
endfunction()
